windowrule = tag +editors, match:class ([cC]ode|[cC]ursor|dev.zed.Zed)
windowrule = tag +agents, match:class (t3-code-desktop)

windowrule = workspace 4 silent, match:tag editors
windowrule = workspace 5 silent, match:tag agents
