-- App-specific window/layer rules (migrated from apps.conf)
-- Loads every module under apps/ in the original order.
---@module 'hl'

require("apps.1password")
require("apps.audacious")
require("apps.bitwarden")
require("apps.browser")
require("apps.editors")
require("apps.hyprshot")
require("apps.jetbrains")
require("apps.localsend")
require("apps.obsidian")
require("apps.pip")
require("apps.qemu")
require("apps.retroarch")
require("apps.steam")
require("apps.system")
require("apps.terminals")
require("apps.walker")
require("apps.work")
