#!/bin/sh
cd ~
# user preferred settings

#cursor size
export XCURSOR_SIZE=24

# text editor
export EDITOR=/usr/bin/nvim

#browser
export BROWSER=zen-browser
#terminal
export TERM=ghostty
#mail
export MAIL=thunderbird

export GDK_BACKEND=wayland,x11
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
export GTK_THEME=Colloid-Purple-Dark-Catppuccin
export ELECTRON_OZONE_PLATFORM_HINT=auto

# check /usr/local/bin/hyprstart
