#!/bin/sh
cd ~
# user preferred settings

#cursor size
export XCURSOR_SIZE=24

# text editor
export MICRO_TRUECOLOR=1
export EDITOR=/usr/bin/micro

#browser
export BROWSER=zen-browser
#terminal
export TERM=ghostty
#mail
export MAIL=thunderbird

export GDK_BACKEND=wayland,x11 
export QT_QPA_PLATFORM=wayland 
export QT_QPA_PLATFORMTHEME=qt5ct
export GTK_THEME=Colloid-Purple-Dark-Catppuccin

# check /usr/local/bin/hyprstart 
